name: Unzip on Push

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unzip files
      run: |
        mkdir -p extracted
        for file in *.zip; do
          unzip -o "$file" -d extracted
        done

    - name: Commit unzipped files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add extracted/*
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Extracted zip files"
          git push
        fi
