name: Unzip on Push

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Unzip files
      run: |
        mkdir -p extracted
        for file in *.zip; do
          unzip -o "$file" -d extracted
        done

    - name: Commit and push unzipped files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add extracted/*
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Extracted zip files"
          git push git@github.com:SmitChauhan45/Boss-Proj.git HEAD:main
        fi
